using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OCG.DataService.Contract;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;

namespace OCG.DataService.Controllers
{
    /// <summary>
    /// Manage MIM Portal data using windows authentication
    /// </summary>
    [Route("api/mim/win/resources")]
    [ApiController]
    public class MIMResourceWinController : ControllerBase
    {
        private readonly IResourceRepository repo;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="repository">Repository to manage MIM Portal data</param>
        public MIMResourceWinController(IResourceRepository repository)
        {
            this.repo = repository;
        }

        /// <summary>
        /// Initializes the service and cache / refresh the resource management client with its schema
        /// </summary>
        /// <param name="token">Token of the resource management client, if exists</param>
        /// <returns>A guid as token referenced to the cached resource management client</returns>
        /// <response code="200">Request succeeded</response>
        [Authorize]
        [HttpGet("init")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesDefaultResponseType]
        public async Task<ActionResult<string>> Initialize([FromQuery] string token)
        {
            WindowsImpersonationContext wic = null;

            try
            {
                wic = ((WindowsIdentity)User.Identity).Impersonate();

                string result = await Task.Run(() =>
                {
                    return this.repo.Initialize(token, string.Empty);
                });

                return result;
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
            finally
            {
                if (wic != null)
                {
                    wic.Undo();
                }
            }

        }

        /// <summary>
        /// Gets the resource with the given <paramref name="id" />
        /// </summary>
        /// <param name="token">Token of the resource management client, generated by init mothed</param>
        /// <param name="id">The ObjectID of the resource</param>
        /// <param name="attributes">The attributes to fetch, if not specified, only DisplayName will be fetched. Format: &lt;AttributeName&gt;,...</param>
        /// <param name="culture">In which language the schema should be returned, see <a href="https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes" target="_blank">supported culture codes</a></param>
        /// <param name="resolveRef">If set to true, reference attributes will be represented as object instead of guid</param>
        /// <param name="format">Simple: fetch only attributes with value; Full: fetch attributes with schema and permission info</param>
        /// <returns>A single resource object</returns>
        /// <response code="200">Request succeeded</response>
        /// <response code="400"><paramref name="id" /> or <paramref name="token" /> is not present, or resource management client exception</response>
        /// <response code="409"><paramref name="token" /> is invalid or expired</response>
        [Authorize]
        [HttpGet("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesDefaultResponseType]
        public async Task<ActionResult<DSResource>> GetResourceByID(
            [FromQuery, Required] string token, 
            [FromRoute] string id, 
            [FromQuery] string attributes, 
            [FromQuery] string culture = "en-US", 
            [FromQuery] bool resolveRef = false, 
            [FromQuery] string format = "simple")
        {
            WindowsImpersonationContext wic = null;

            try
            {
                wic = ((WindowsIdentity)User.Identity).Impersonate();

                DSResource result = await Task.Run(() =>
                {
                    string[] attributeArray = string.IsNullOrEmpty(attributes) ? null : 
                        attributes.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Select(p => p.Trim()).ToArray();

                    bool includePermission = format.Equals("full", StringComparison.OrdinalIgnoreCase) ? true : false;

                    return this.repo.GetResourceByID(token, id, attributeArray, culture, includePermission, resolveRef);
                });

                return result;
            }
            catch (ArgumentException e)
            {
                return this.BadRequest(e.Message);
            }
            catch (InvalidOperationException e)
            {
                return this.Conflict(e.Message);
            }
            catch (Exception e)
            {
                return this.BadRequest(e.Message);
            }
            finally
            {
                if (wic != null)
                {
                    wic.Undo();
                }
            }
        }

        /// <summary>
        /// Gets resources with the given <paramref name="query" />
        /// </summary>
        /// <param name="token">Token of the resource management client, generated by init mothed</param>
        /// <param name="query">The xpath query to search resources</param>
        /// <param name="attributes">The attributes to fetch, if not specified, only DisplayName will be fetched. Format: &lt;AttributeName&gt;,...</param>
        /// <param name="pageSize">Page size of the returned resources</param>
        /// <param name="index">Starting index in the whole result queue</param>
        /// <param name="resolveRef">If set to true, reference attributes will be represented as object instead of guid</param>
        /// <param name="orderBy">Sorting attributes definition. Format: &lt;AttributeName&gt;:&lt;asc|desc|ascending|descending&gt;,...</param>
        /// <returns>A set of resource objects with totalCount and hastMoreItems indicator</returns>
        /// <response code="200">Request succeeded</response>
        /// <response code="400"><paramref name="query" /> or <paramref name="token" /> is not present, or resource management client exception</response>
        /// <response code="409"><paramref name="token" /> is invalid or expired</response>
        [Authorize]
        [HttpGet("search")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesDefaultResponseType]
        public async Task<ActionResult<DSResourceSet>> GetResourceByQuery(
            [FromQuery, Required] string token, 
            [FromQuery, Required] string query,
            [FromQuery] string attributes,
            [FromQuery] int pageSize = 0,
            [FromQuery] int index = 0,
            [FromQuery] bool resolveRef = false,
            [FromQuery] string orderBy = null)
        {
            WindowsImpersonationContext wic = null;

            try
            {
                wic = ((WindowsIdentity) User.Identity).Impersonate();

                DSResourceSet result = await Task.Run(() =>
                {
                    string[] attributeArray = string.IsNullOrEmpty(attributes) ? null :
                        attributes.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Select(p => p.Trim()).ToArray();

                    Dictionary<string, string> sortingAttributes = new Dictionary<string, string>();
                    if (!string.IsNullOrEmpty(orderBy))
                    {
                        foreach (string sortingAttribute in
                            orderBy.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Select(p => p.Trim()))
                        {
                            string[] sortingDef = sortingAttribute
                                .Split(":".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Select(p => p.Trim()).ToArray();
                            if (sortingDef.Length == 2)
                            {
                                sortingAttributes.Add(sortingDef[0], sortingDef[1]);
                            }
                            else
                            {
                                throw new ArgumentException("invalid sorting attributes");
                            }
                        }
                    }

                    foreach (string key in sortingAttributes.Keys)
                    {
                        if (!attributeArray.Contains(key))
                        {
                            throw new ArgumentException("loading attributes don't include sorting attributes");
                        }
                    }

                    return this.repo.GetResourceByQuery(token, query, attributeArray, pageSize, index, resolveRef, sortingAttributes);
                });

                return result;
            }
            catch (ArgumentException e)
            {
                return this.BadRequest(e.Message);
            }
            catch (InvalidOperationException e)
            {
                return this.Conflict(e.Message);
            }
            catch (Exception e)
            {
                return this.BadRequest(e.Message);
            }
            finally
            {
                if (wic != null)
                {
                    wic.Undo();
                }
            }
        }

        /// <summary>
        /// Deletes the resource with the given <paramref name="id" />
        /// </summary>
        /// <param name="token">Token of the resource management client, generated by init mothed</param>
        /// <param name="id">The ObjectID of the resource</param>
        /// <returns>This method doesn't have return value</returns>
        /// <response code="200">Request succeeded</response>
        /// <response code="400"><paramref name="id" /> or <paramref name="token" /> is not present, or resource management client exception</response>
        /// <response code="409"><paramref name="token" /> is invalid or expired</response>
        [Authorize]
        [HttpDelete("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesDefaultResponseType]
        public async Task<ActionResult> DeleteResource(
            [FromQuery, Required] string token,
            [FromRoute] string id)
        {
            WindowsImpersonationContext wic = null;

            try
            {
                wic = ((WindowsIdentity) User.Identity).Impersonate();

                await Task.Run(() =>
                {
                    this.repo.DeleteResource(token, id);
                });

                return this.Ok();
            }
            catch (ArgumentException e)
            {
                return this.BadRequest(e.Message);
            }
            catch (InvalidOperationException e)
            {
                return this.Conflict(e.Message);
            }
            catch (Exception e)
            {
                return this.BadRequest(e.Message);
            }
            finally
            {
                if (wic != null)
                {
                    wic.Undo();
                }
            }
        }

        /// <summary>
        /// Creates the given <paramref name="resource" />
        /// </summary>
        /// <param name="token">Token of the resource management client, generated by init mothed</param>
        /// <param name="resource">The resource to be created. ObjectType must exist as a property</param>
        /// <returns>The ObjectID of the created resource</returns>
        /// <response code="200">Request succeeded</response>
        /// <response code="400"><paramref name="resource" /> or <paramref name="token" /> is not present, or resource management client exception</response>
        /// <response code="409"><paramref name="token" /> is invalid or expired</response>
        [Authorize]
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status417ExpectationFailed)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesDefaultResponseType]
        public async Task<ActionResult<string>> CreateResource(
            [FromQuery, Required] string token,
            [FromBody] DSResource resource)
        {
            WindowsImpersonationContext wic = null;

            try
            {
                wic = ((WindowsIdentity) User.Identity).Impersonate();

                string result = await Task.Run(() =>
                {
                    return this.repo.CreateResource(token, resource);
                });

                return result;
            }
            catch (ArgumentException e)
            {
                return this.BadRequest(e.Message);
            }
            catch (InvalidOperationException e)
            {
                return this.Conflict(e.Message);
            }
            catch (Exception e)
            {
                return this.BadRequest(e.Message);
            }
            finally
            {
                if (wic != null)
                {
                    wic.Undo();
                }
            }
        }

        /// <summary>
        /// Updates the given <paramref name="resource" />
        /// </summary>
        /// <param name="token">Token of the resource management client, generated by init mothed</param>
        /// <param name="resource">The resource to be updated. ObjectType and ObjectID must exist as properties</param>
        /// <returns>Empty if request succeeded, "authorization required" if approval required</returns>
        /// <response code="200">Request succeeded</response>
        /// <response code="204">Request accepted but need authorization</response>
        /// <response code="400"><paramref name="resource" /> or <paramref name="token" /> is not present, or resource management client exception</response>
        /// <response code="409"><paramref name="token" /> is invalid or expired</response>
        [Authorize]
        [HttpPatch]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status202Accepted)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesDefaultResponseType]
        public async Task<ActionResult<string>> UpdateResource(
            [FromQuery, Required] string token,
            [FromBody] DSResource resource)
        {
            WindowsImpersonationContext wic = null;

            try
            {
                wic = ((WindowsIdentity) User.Identity).Impersonate();

                await Task.Run(() =>
                {
                    this.repo.UpdateResource(token, resource);
                });

                return Ok();
            }
            catch (ArgumentException e)
            {
                return this.BadRequest(e.Message);
            }
            catch (InvalidOperationException e)
            {
                return this.Conflict(e.Message);
            }
            catch (AuthZRequiredException e)
            {
                return Accepted(e.Message);
            }
            catch (Exception e)
            {
                return this.BadRequest(e.Message);
            }
            finally
            {
                if (wic != null)
                {
                    wic.Undo();
                }
            }
        }


    }
}